repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--safe, --quiet, --line-length, "100"]
        language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=100"]
        additional_dependencies: [flake8-typing-imports==1.7.0]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
    -   id: pyupgrade
        language_version: python3
