name: windup_ide_tests

on:
  pull_request:
    paths-ignore:
      - "**/data_control.py"


jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@main

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Pre-Commit Checks
        run: |
          python -m pip install pre-commit
          pre-commit run -a
      - name: Analysis (git diff)
        if: failure()
        run: git diff
